In [1]:
# Answer 1

import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)


int64


In [2]:
# Answer 2

arr = np.array([1.5, 2.6, 3.7])  # Example array given in the image
is_float64 = arr.dtype == np.float64
print(is_float64)


True


In [3]:
# Answer 3

arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


In [4]:
# ANswer 4

arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1. 2. 3. 4. 5.]


In [5]:
# Answer 5

arr = np.array([1.5, 2.6, 3.7], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1.5 2.6 3.7]


In [6]:
# Answer 6

def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([1.5, 2.6, 3.7])
print(array_attributes(arr))


((3,), 3, dtype('float64'))


In [7]:
# Answer 7

def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2], [3, 4]])
print(array_dimension(arr))


2


In [8]:
# Answer 8

import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize          # Size of one element in bytes
    total_size = arr.nbytes           # Total size of the array in bytes
    return item_size, total_size

# Example usage
arr = np.array([1, 2, 3, 4, 5])
print(item_size_info(arr))


(8, 40)


In [9]:
# ANswer 9

import numpy as np

def array_strides(arr):
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))


(24, 8)


In [10]:
# Answer 10

import numpy as np

def shape_stride_relationship(arr):
    """
    Returns the shape and strides of a NumPy array.
    
    Parameters:
    arr (numpy.ndarray): Input NumPy array.
    
    Returns:
    tuple: A tuple containing the shape and strides of the array.
    """
    shape = arr.shape
    strides = arr.strides
    return shape, strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))  # Output: ((2, 3), (24, 8))


((2, 3), (24, 8))


In [11]:
# Answer 11

import numpy as np

def create_zeros_array(n):
    """
    Creates a NumPy array of zeros with n elements.
    
    Parameters:
    n (int): The number of elements in the array.
    
    Returns:
    numpy.ndarray: An array of zeros with n elements.
    """
    return np.zeros(n)

# Example usage
n = 5
print(create_zeros_array(n))  # Output: [0. 0. 0. 0. 0.]


[0. 0. 0. 0. 0.]


In [12]:
# Answer 12

import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

# Example usage
matrix = create_ones_matrix(3, 4)
print(matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Answer 13

import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage
array = generate_range_array(1, 10, 2)
print(array)


[1 3 5 7 9]


In [14]:
# Answer 14

import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
array = generate_linear_space(0.0, 5.0, 6)
print(array)


[0. 1. 2. 3. 4. 5.]


In [15]:
# Answer 15

import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

# Example usage
matrix = create_identity_matrix(4)
print(matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# Answer 16

import numpy as np

def list_to_numpy_array(lst):
    return np.array(lst)

# Example usage
python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print(numpy_array)


[1 2 3 4 5]


In [17]:
# Answer 17

import numpy as np

# Create an initial NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Use numpy.view() to create a new view of the same data
view_array = original_array.view()

# Modify the view_array to show that it affects the original_array
view_array[0] = 10

# Print both arrays to see the effect
print("Original Array:", original_array)
print("View Array:", view_array)


Original Array: [10  2  3  4  5]
View Array: [10  2  3  4  5]


In [18]:
# Answer 18

import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along the first axis (rows)
result_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result_axis0)

# Concatenate along the second axis (columns)
result_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", result_axis1)


Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
# ANswer 19

import numpy as np

# Create two NumPy arrays with different shapes but compatible for horizontal concatenation
array1 = np.array([[1, 2, 3], [4, 5, 6]])   # Shape (2, 3)
array2 = np.array([[7, 8], [9, 10]])         # Shape (2, 2)

# Concatenate the arrays horizontally (along axis 1)
result = np.concatenate((array1, array2), axis=1)

print("Concatenated Array:\n", result)


Concatenated Array:
 [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [20]:
# Answer 20

import numpy as np

def vertical_stack(arrays):
    return np.vstack(arrays)

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15]])

# Stack the arrays vertically
result = vertical_stack([array1, array2, array3])
print("Vertically Stacked Array:\n", result)


Vertically Stacked Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [21]:
# Answer 21

import numpy as np

def range_array(start, stop, step):
    # Use np.arange to generate an array from start to stop (inclusive) with the given step
    if step == 0:
        raise ValueError("Step size must be non-zero")
    if step > 0 and start > stop:
        raise ValueError("For positive step size, start must be less than or equal to stop")
    if step < 0 and start < stop:
        raise ValueError("For negative step size, start must be greater than or equal to stop")
    
    # Adjust the stop value to be inclusive
    if step > 0:
        stop += 1
    
    return np.arange(start, stop, step)

# Example usage
array = range_array(1, 10, 2)
print("Array:", array)


Array: [1 3 5 7 9]


In [22]:
# Answer 22

import numpy as np

def generate_equally_spaced_array(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
array = generate_equally_spaced_array(0, 1, 10)
print("Equally Spaced Array:", array)


Equally Spaced Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
# Answer 23

import numpy as np

def generate_log_space(start, stop, num):
    return np.logspace(np.log10(start), np.log10(stop), num)

# Example usage
array = generate_log_space(1, 1000, 5)
print("Logarithmically Spaced Array:", array)


Logarithmically Spaced Array: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [24]:
# Answer 24

import pandas as pd
import numpy as np

# Generate a NumPy array with random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))

# Create a DataFrame from the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

print("DataFrame:\n", df)


DataFrame:
    Column1  Column2  Column3
0       80        2       29
1       13       85       99
2       92       10       43
3       64       79       76
4       61       78       27


In [25]:
# Answer 25

import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])

# Example usage
data = {
    'A': [10, -5, 15, -20, 25],
    'B': [-1, 2, -3, 4, -5]
}
df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

# Replace negative values in column 'A'
replace_negatives_with_zeros(df, 'A')

print("DataFrame after replacing negatives in column 'A':\n", df)


Original DataFrame:
     A  B
0  10 -1
1  -5  2
2  15 -3
3 -20  4
4  25 -5
DataFrame after replacing negatives in column 'A':
     A  B
0  10 -1
1   0  2
2  15 -3
3   0  4
4  25 -5


In [26]:
# Answer 26

import numpy as np

# Example 1D NumPy array
array = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = array[2]
print("3rd Element:", third_element)


3rd Element: 30


In [27]:
# Answer 27

import numpy as np

# Example 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = array_2d[1, 2]
print("Element at (1, 2):", element)


Element at (1, 2): 6


In [28]:
# ANswer 28

import numpy as np

# Example NumPy array
array = np.array([1, 6, 3, 8, 5, 10])

# Extract elements greater than 5
elements_greater_than_5 = array[array > 5]
print("Elements greater than 5:", elements_greater_than_5)


Elements greater than 5: [ 6  8 10]


In [29]:
# Answer 29

import numpy as np

# Example NumPy array
array = np.array([10, 20, 30, 40, 50, 60, 70])

# Extract elements from index 2 to 5 (inclusive)
sliced_array = array[2:6]
print("Sliced Array (index 2 to 5):", sliced_array)


Sliced Array (index 2 to 5): [30 40 50 60]


In [30]:
# Answer 30
import numpy as np

# Example 2D NumPy array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Extract the sub-array [[2, 3], [5, 6]]
sub_array = array_2d[0:2, 1:3]
print("Sub-array [[2, 3], [5, 6]]:\n", sub_array)


Sub-array [[2, 3], [5, 6]]:
 [[2 3]
 [6 7]]


In [31]:
# Answer 31
import numpy as np

def extract_elements(array_2d, indices):
    return array_2d[indices]

# Example usage
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = (np.array([0, 1, 2]), np.array([2, 1, 0]))  # Extract elements (0,2), (1,1), (2,0)
extracted_elements = extract_elements(array_2d, indices)
print("Extracted Elements:", extracted_elements)


Extracted Elements: [3 5 7]


In [32]:
# Answer 32

import numpy as np

def filter_elements(array, threshold):
    return array[array > threshold]

# Example usage
array = np.array([1, 5, 7, 10, 3])
threshold = 4
filtered_array = filter_elements(array, threshold)
print("Filtered Elements:", filtered_array)


Filtered Elements: [ 5  7 10]


In [33]:
# Answer 33
import numpy as np

def extract_from_3d_array(array_3d, x_indices, y_indices, z_indices):
    return array_3d[x_indices, y_indices, z_indices]

# Example usage
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
x_indices = np.array([0, 1, 1])
y_indices = np.array([0, 1, 0])
z_indices = np.array([2, 1, 0])
extracted_elements = extract_from_3d_array(array_3d, x_indices, y_indices, z_indices)
print("Extracted Elements from 3D Array:", extracted_elements)


Extracted Elements from 3D Array: [ 3 11  7]


In [34]:
# Answer 34

import numpy as np

def filter_with_conditions(array, condition1, condition2):
    return array[condition1 & condition2]

# Example usage
array = np.array([1, 2, 3, 4, 5, 6])
condition1 = array > 2
condition2 = array < 5
filtered_array = filter_with_conditions(array, condition1, condition2)
print("Filtered Elements with Both Conditions:", filtered_array)


Filtered Elements with Both Conditions: [3 4]


In [35]:
# Answer 35

import numpy as np

def extract_elements_by_indices(array_2d, row_indices, col_indices):
    return array_2d[row_indices, col_indices]

# Example usage
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
extracted_elements = extract_elements_by_indices(array_2d, row_indices, col_indices)
print("Extracted Elements by Row and Column Indices:", extracted_elements)


Extracted Elements by Row and Column Indices: [2 6 7]


In [36]:
# Answer 36

import numpy as np

def add_scalar_to_array(array, scalar):
    return array + scalar

# Example usage
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar = 5
result_array = add_scalar_to_array(array, scalar)
print("Array after Adding Scalar:", result_array)


Array after Adding Scalar: [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
# Answer 37

import numpy as np

def multiply_rows_by_array(arr1, arr2):
    return arr2 * arr1

# Example usage
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
result_array = multiply_rows_by_array(arr1, arr2)
print("Result of Multiplying Rows by Array:", result_array)


Result of Multiplying Rows by Array: [[ 4 10 18]
 [ 7 16 27]]


In [38]:
# Answer 38

import numpy as np

arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],       # Shape (4, 3)
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

# Reshape arr1 to (1, 1, 4) and arr2 to (4, 3, 1)
arr1_reshaped = arr1[:, :, np.newaxis]  # Shape (1, 4, 1)
arr2_reshaped = arr2[:, np.newaxis, :]  # Shape (4, 1, 3)

result = arr2_reshaped + arr1_reshaped
result = result.squeeze()  # Shape (4, 3)


In [39]:
# Answer 39

import numpy as np

arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])       # Shape (1, 3)

result = arr1 + arr2


In [40]:
# Answer 40

import numpy as np

arr1 = np.array([[1, 2, 3],        # Shape (2, 3)
                 [4, 5, 6]])
arr2 = np.array([[7, 8],            # Shape (2, 2)
                 [9, 10]])

# To multiply, we need compatible shapes. We can use np.dot for matrix multiplication instead.
result = np.dot(arr1, arr2)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [41]:
# Answer 41

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

column_mean = np.mean(arr, axis=0)


In [42]:
# Answer 42
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row_max = np.max(arr, axis=1)


In [43]:
# Answer 43
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

indices = np.argmax(arr, axis=0)


In [44]:
# Answer 44

import numpy as np
from numpy.lib.stride_tricks import as_strided

def moving_sum(arr, window_size):
    if window_size > arr.shape[1]:
        raise ValueError("Window size must be less than or equal to number of columns")

    shape = (arr.shape[0], arr.shape[1] - window_size + 1, window_size)
    strides = (arr.strides[0], arr.strides[1], arr.strides[1])
    sub_matrices = as_strided(arr, shape=shape, strides=strides)
    return np.sum(sub_matrices, axis=2)

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

window_size = 2
result = moving_sum(arr, window_size)


In [45]:
# Answer 46
import numpy as np

def reshape_array(arr, m, n):
    return arr.reshape(m, n)


In [46]:
# Answer 47
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()


In [47]:
# Answer 48
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)


In [48]:
# Answer 49
import numpy as np

def split_array(arr, indices_or_sections, axis):
    return np.split(arr, indices_or_sections, axis=axis)


In [49]:
# Answer 50

import numpy as np

def insert_and_delete(arr, insert_index, insert_values, delete_index):
    arr = np.insert(arr, insert_index, insert_values)
    arr = np.delete(arr, delete_index)
    return arr


In [50]:
# ANswer 51

import numpy as np

arr1 = np.random.randint(1, 10, size=(3, 3))
arr2 = np.arange(1, 11).reshape(1, 10)[:arr1.shape[0], :arr1.shape[1]]
result = arr1 + arr2


In [51]:
# Answer 52
import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2


In [52]:
# Answer 53

import numpy as np

arr1 = np.random.randint(1, 10, size=(3, 3))
arr2 = np.arange(1, 6)
result = arr1 * arr2[:arr1.shape[1]]


In [53]:
# Answer 54

import numpy as np

arr1 = np.arange(2, 12, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2


In [54]:
# Answer 55

import numpy as np

arr1 = np.arange(1, 6)
arr2 = np.flip(arr1)
result = np.power(arr1, arr2)


In [55]:
# Answer 56

import numpy as np

arr1 = np.arange(1, 6)
arr2 = np.flip(arr1)
result = np.power(arr1, arr2)


In [56]:
# Answer 57

import numpy as np

def extract_uppercase(array):
    return np.array([ ''.join(c for c in s if c.isupper()) for s in array ])


In [57]:
# Answer 58

import numpy as np

def replace_substring(array, old_substring, new_substring):
    return np.char.replace(array, old_substring, new_substring)


In [58]:
# Answer 59

import numpy as np

def concatenate_strings(array, separator=''):
    return np.char.add(array[:-1], np.char.add(separator, array[1:]))


In [59]:
# Answer 60

import numpy as np

def longest_string_length(array):
    return np.max(np.char.str_len(array))


In [60]:
# Answer 61
import numpy as np

# Generate dataset
dataset = np.random.randint(1, 1001, size=100)

# Compute statistics
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

mean, median, variance, std_dev


(513.81, 526.5, 85274.73389999999, 292.0183793873255)

In [61]:
# Answer 62

import numpy as np

# Generate dataset
data = np.random.uniform(1, 100, 50)

# Compute percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

percentile_25, percentile_75


(24.601398933510033, 74.40945197297087)

In [62]:
# Answer 63

import numpy as np

# Example arrays
array1 = np.random.rand(100)
array2 = np.random.rand(100)

# Compute correlation coefficient
correlation_matrix = np.corrcoef(array1, array2)
correlation_coefficient = correlation_matrix[0, 1]

correlation_coefficient


-0.07715211222962903

In [63]:
# Answer 64

import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Multiplication Result:\n", result)


Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [64]:
# Answer 65

import numpy as np

# Create an array of 50 integers between 10 and 1000
array = np.random.randint(10, 1000, size=50)

# Calculate percentiles
percentile_10 = np.percentile(array, 10)
percentile_50 = np.percentile(array, 50)  # This is the median
percentile_90 = np.percentile(array, 90)

# Calculate quartiles
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

print("Array:\n", array)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)



Array:
 [476 512 286 861 565 449 832 923  71 394 131 780 281 410 121 323  66 612
 197 457 190 373 711 609 122 213 562 378 444 842 967 829 607 850 212 422
 668 239 938 499 318 288 308 780 528 735 556 294 493 530]
10th Percentile: 184.10000000000002
50th Percentile (Median): 466.5
90th Percentile: 842.8
First Quartile (25th Percentile): 289.5
Third Quartile (75th Percentile): 654.0


In [65]:
# Answer 66

import numpy as np

# Create an array of integers
array = np.array([10, 20, 30, 40, 50])

# Specify the element to find
element = 30

# Find the index of the element
index = np.where(array == element)[0][0]

print("Array:", array)
print("Index of element", element, ":", index)


Array: [10 20 30 40 50]
Index of element 30 : 2
